name: Bug Report
description: 反馈 KiteBlog 的问题
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ciyuan1234
body:
  - type: markdown
    attributes:
      value: |
        感谢反馈 KiteBlog 的问题。
  - type: textarea
    id: bug-description
    attributes:
      label: 问题描述
      description: 请清楚描述你遇到的问题。
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: 复现步骤
      description: 请列出复现方式。
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望行为
      description: 说明你预期应该发生什么。
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
  - type: input
    id: browser
    attributes:
      label: 浏览器
      placeholder: e.g. chrome, safari
  - type: textarea
    id: additional-context
    attributes:
      label: 补充信息
      description: 可以添加截图、日志或其他背景。
